
export const ROUTES = {
    ONBOARDING: 'OnboardingScreen',
    CREATE_ACCOUNT: 'CreateAccountScreen',
    Login_SCREEN: 'LoginScreen',
    FORGOT_PASSWORD: 'ForgotPasswordScreen',
    Varification_SCREEN: 'VerificationCodeScreen',
    RESET_PASSWORD: 'ResetPasswordScreen',
    HOMESCREEN: 'HomeScreen',
    PRODUCT_DETAIL: 'ProductDetailScreen',
    CARTSCREEN: 'CartScreen',
    SEARCH_SCREEN: 'SearchScreen',
    SAVED_SCREEN: 'SavedScreen',
    NEWCARD_SCREEN: 'NewCardScreen',
    ACCOUNT_SCREEN: 'AccountScreen',
    TABS: "MainTabs",
    MY_ORDERS: "MyOrdersScreen",
    CHECKOUT_SCREEN: "CheckoutScreen",
    FAQ_Screen: "FAQScreen",
    Help_Center_Screen: "HelpCenterScreen",
    ADDRESS_SCREEN: "AddressScreen",
};
